# Generated by GithubCopilot
"""
Asistente de Planificación de Viajes – CLI entry point.

Recoge las preferencias del usuario por consola, ejecuta el grafo de
planificación (LangGraph) y muestra el itinerario resultante.

Security: input is validated inside the graph (Node 1).
Accessibility: clear prompts with default values in parentheses.
"""

from __future__ import annotations

import logging
import os
import sys

from dotenv import load_dotenv

# Load .env before any other import that may need API keys
load_dotenv()

from graph import run_graph  # noqa: E402


def _setup_logging() -> None:
    """Configure basic logging to stderr."""
    logging.basicConfig(
        level=logging.INFO,
        format="%(asctime)s [%(levelname)s] %(name)s – %(message)s",
        stream=sys.stderr,
    )


def _prompt(label: str, default: str = "") -> str:
    """Display a prompt with an optional default value."""
    suffix = f" [{default}]" if default else ""
    value = input(f"{label}{suffix}: ").strip()
    return value or default


def main() -> None:
    """Interactive CLI flow."""
    _setup_logging()

    # Verify API key is present
    if not os.getenv("OPENAI_API_KEY"):
        print(
            "❌ Error: OPENAI_API_KEY no encontrada.\n"
            "   Crea un archivo .env basándote en .env.example y establece tu clave.",
            file=sys.stderr,
        )
        sys.exit(1)

    print("=" * 60)
    print("  🌍  Asistente de Planificación de Viajes")
    print("=" * 60)
    print()

    destination = _prompt("Destino deseado (ej. Tokio, Japón)")
    budget = _prompt("Presupuesto (bajo / medio / alto)", "medio")
    trip_type = _prompt("Tipo de viaje (aventura / relax / cultural / familiar)", "cultural")

    duration_str = _prompt("Duración en días", "5")
    try:
        duration = int(duration_str)
    except ValueError:
        print("⚠️  Duración no válida; se usará 5 días.", file=sys.stderr)
        duration = 5

    print()
    print("⏳ Generando tu plan de viaje personalizado…")
    print("   (esto puede tardar ~30-60 segundos)")
    print()

    result = run_graph(
        destination=destination,
        budget=budget,
        trip_type=trip_type,
        duration=duration,
    )

    # Display result
    if result.get("validated"):
        print(result.get("final_itinerary", "Sin itinerario generado."))
    else:
        print("❌  No se pudo generar el itinerario:")
        for err in result.get("validation_errors", []):
            print(f"   • {err}")
        sys.exit(1)


if __name__ == "__main__":
    main()
