package CTTI;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

// Generated 01-jun-2012 11:44:53 by Hibernate Tools 3.4.0.CR1


//import org.hibernate.annotations.NamedNativeQueries;
//import org.hibernate.annotations.NamedNativeQuery;

/**
 * TbEquip generated by hbm2java
 * 
 * @author Accenture
 * 
 */
@Entity
@Table(name = "MONEDA", schema = "sefac_adm")
@NamedQueries(
      {
            @NamedQuery(name= "TbMoneda.findAllOrderById", query="FROM TbMoneda t ORDER BY t.id")
      }
)
public class TbMoneda implements java.io.Serializable {
	
	private Integer id_moneda = null;
	private String id_moneda_gecat = null;
	private String descripcion = null;
	private String descripcion_corta = null;
	
	/**
	 * @return the id_moneda
	 */
	@Id
	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "nom_SEQ")
	@SequenceGenerator(name = "nom_SEQ", sequenceName = "sefac_adm.moneda_sequence", allocationSize = 1)	
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId_moneda() {
		return id_moneda;
	}

	/**
	 * @param id_moneda the id_moneda to set
	 */
	public void setId_moneda(Integer id_moneda) {
		this.id_moneda = id_moneda;
	}

	/**
	 * @return the id_moneda_gecat
	 */
	@Column(name = "moneda_gecat", nullable = true)
	public String getId_moneda_gecat() {
		return id_moneda_gecat;
	}

	/**
	 * @param id_moneda_gecat the id_moneda_gecat to set
	 */
	public void setId_moneda_gecat(String id_moneda_gecat) {
		this.id_moneda_gecat = id_moneda_gecat;
	}

	/**
	 * @return the descripcion
	 */
	@Column(name = "descripcion", nullable = true)
	public String getDescripcion() {
		return descripcion;
	}

	/**
	 * @param descripcion the descripcion to set
	 */
	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	/**
	 * @return the descripcion_corta
	 */
	@Column(name = "descripcion_corta", nullable = true)
	public String getDescripcion_corta() {
		return descripcion_corta;
	}

	/**
	 * @param descripcion_corta the descripcion_corta to set
	 */
	public void setDescripcion_corta(String descripcion_corta) {
		this.descripcion_corta = descripcion_corta;
	}
	
	
	

}
